FROM alpine:latest

ARG PB_VERSION=0.18.9

RUN apk add --no-cache \
    unzip \
    ca-certificates

ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

COPY . .

EXPOSE 8090

CMD ["./pocketbase", "serve"]
